
export const tinyDailyTasks: string[] = [
  "Hold a plank for 60 seconds.",
  "Do 30 jumping jacks.",
  "Drink a full glass of water right now.",
  "Take 10 deep, calming breaths.",
  "Stretch your hamstrings for 30 seconds on each side.",
  "Do 15 bodyweight squats.",
  "Walk around for 5 minutes.",
  "Write down 3 things you are grateful for.",
  "Do 10 push-ups (or knee push-ups).",
  "Eat a piece of fruit.",
  "Tidy up your workspace for 5 minutes.",
  "Hold a wall sit for 45 seconds.",
  "Do 20 crunches.",
  "Smile at the next person you see.",
  "Reach for your toes and hold for 30 seconds.",
  "Step outside for some fresh air for 2 minutes.",
  "Do 15 lunges (each leg).",
  "Stand up and stretch your arms overhead.",
  "Read one page of a book.",
  "Unfollow a social media account that doesn't make you feel good.",
  "Do 20 calf raises.",
  "Plan a healthy meal for today.",
  "Roll your shoulders back and down 5 times.",
  "Compliment a friend or family member.",
  "Do a 30-second side plank on each side.",
  "Write down one small, achievable goal for tomorrow.",
  "Listen to one of your favorite upbeat songs.",
  "Avoid sugary drinks for the rest of the day.",
  "Do 1-minute of high knees.",
  "Put your phone away for the next 15 minutes.",
  "Do 10 burpees.",
  "Meditate for 3 minutes.",
  "Foam roll your back for 2 minutes.",
  "Write a positive affirmation 5 times.",
  "Watch a short, educational video.",
  "Do 15 tricep dips on a chair.",
  "Clean one small thing you've been putting off.",
  "Hold a tree pose for 30 seconds on each side.",
  "Send a thank-you text to someone.",
  "Do 20 mountain climbers.",
  "Drink a cup of green tea.",
  "Do some neck stretches to relieve tension.",
  "Plan your outfit for tomorrow.",
  "Hold a glute bridge for 60 seconds.",
  "Make your bed.",
  "Do 10-minutes of light cardio.",
  "Organize your computer desktop.",
  "Practice mindful eating with your next snack.",
  "Do 5 slow, controlled push-ups.",
  "Journal for 5 minutes about your day.",
  "Do 30 seconds of arm circles in each direction.",
  "Declutter one drawer or shelf.",
  "Listen to a 5-minute podcast.",
  "Do some wrist and ankle rotations.",
  "Set an intention for the rest of your day.",
  "Floss your teeth.",
  "Do 12 alternating superman exercises.",
  "Go to bed 15 minutes earlier tonight.",
  "Do 1 minute of jogging in place.",
  "Visualize achieving one of your goals.",
  "Take a social media break for 30 minutes."
];
